### ISSUE TITLE
Remote Driver with Selenium Grid in Docker

### ISSUE THREAD

**Issue by IOANNB4R** [wkeeling/selenium-wire#632]
I'm trying to use [Selenium Grid in Docker](https://github.com/SeleniumHQ/docker-selenium) with selenium-wire but unfortunately, it doesn't work. It works with the general Selenium library though:

```python
from selenium import webdriver

driver = webdriver.Remote('http://127.0.0.1:4444', options=webdriver.ChromeOptions())

driver.get('https://python.org')
driver.save_screenshot('screenshot.png')

driver.quit()
```

But when I use selenium-wire, it just gets stuck. I use the following code:

```python
from seleniumwire import webdriver

driver = webdriver.Remote('http://127.0.0.1:4444', options=webdriver.ChromeOptions())

driver.get('https://python.org')
driver.save_screenshot('screenshot.png')

driver.quit()
```

Also, I noticed: when I use Selenium, the Grid Panel looks like this:

<img width="1273" alt="selenium" src="https://user-images.githubusercontent.com/106876808/207850711-c159dca3-a1dd-4b1c-a3a5-b331c14f62e4.png">

But when I use selenium-wire, it looks like that:

<img width="1271" alt="selenium-wire" src="https://user-images.githubusercontent.com/106876808/207850984-b1491709-a086-4a40-a5cd-1466cdb42c6e.png">

The full JSON string it shows:
```json
{
  "acceptInsecureCerts": true,
  "browserName": "firefox",
  "goog:chromeOptions": {
    "extensions": [],
    "args": []
  },
  "moz:debuggerAddress": true,
  "pageLoadStrategy": "normal",
  "proxy": {
    "proxyType": "manual",
    "httpProxy": "[::ffff:127.0.0.1]:50540",
    "sslProxy": "[::ffff:127.0.0.1]:50540"
  }
}
```

**Comment by felipeacunago** [comment]
Hi!,

you need to set the proxy server to point the VM/docker that runs the code. For example your code should be:

```python
from selenium import webdriver

chrome_options = webdriver.ChromeOptions()
# you are going to tell selenium the IP where the code will run
# replace scrap with the IP, I use scrap because my docker-compose file uses that name
chrome_options.add_argument('--proxy-server=scrap:8087')

# replace chrome with the IP of the selenium docker, I use chrome because my docker-compose file uses that name
driver = webdriver.Remote(
    command_executor='http://chrome:4444/wd/hub',
    desired_capabilities=chrome_options.to_capabilities(),
    seleniumwire_options={
        'auto_config': False,
        'addr': '0.0.0.0',
        'port': 8087
    })

driver.get('https://python.org')
driver.save_screenshot('screenshot.png')

driver.quit()
```

And then you should expose that port, I usually run this in a docker-compose environment so I do it like this:

```
version: '3'

services:
  scrap: #image build using your code
    build:
      context: .
      dockerfile: ./scrap/Dockerfile
    ports:
      - "8087:8087" # I expose the port
    healthcheck:
      test: "exit 0"
      
  chrome: #selenium image
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
    shm_size: '2gb'
```
Hope it helps!
