### ISSUE TITLE
Remote Webdriver not capturing requests

### ISSUE THREAD

**Issue by hnandiwada** [wkeeling/selenium-wire#644]
We are running a Selenium Grid with a Chrome node in Docker. Our docker-compose looks like this:
```
version: "3"
services:
  chrome:
    image: seleniarm/node-chromium:latest
    shm_size: 2gb
    depends_on:
      - seleniarm-hub
    environment:
      - SE_EVENT_BUS_HOST=seleniarm-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=10
      - SE_NODE_MAX_INSTANCES=10
    ports:
      - 5555:5555

  seleniarm-hub:
    image: seleniarm/hub:latest
    container_name: seleniarm-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
```
(I am using an M1 Mac, hence seleniarm instead of selenium.)
On the local machine, we create a remote driver and it seems that we successfully navigate to a URL. However, the requests attached to the driver always come up empty. 
Code on the machine:
```
    options = webdriver.ChromeOptions()
    options.headless = True
    cap = DesiredCapabilities.CHROME
    cap["goog:loggingPrefs"] = {"performance": "ALL"}
    seleniumwire_options = {
        "addr": "127.0.0.1",
        # "addr": "0.0.0.0",
        "auto_config": False,
        "port": 5555,
    }
    driver = webdriver.Remote(
        # command_executor=f"{HUB_URL}:4444/wd/hub",
        command_executor=HUB_URL, # <---- "http://localhost:4444/wd/hub"
        # command_executor="http://selenium-hub:444/wd/hub",
        options=options,
        desired_capabilities=cap,
        seleniumwire_options=seleniumwire_options,
    )
    driver.get(url)
    time.sleep(3)
    requests = driver.requests # <---- showing up as empty list
```
We confirmed that `driver.current_url` is the same as the URL we want to query. When we use the Chrome driver without Docker, everything works perfectly as expected:
```
    driver = webdriver.Chrome(
        options=options, service=chromeService(ChromeDriverManager().install())
    )
```
We've tried a whole lot of flags to try to get this to work with no dice. How can we make sure we're sniffing the network?
